# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 8
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.cache/wt [current_project]
set_property parent.project_path /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/student_28/Files/Lab_4/pulpino_students/rtl/config.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/includes/axi_bus.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_event_unit/include/defines_event_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/include/apu_macros.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/include/zeroriscy_config.sv
}
set_property file_type "Verilog Header" [get_files /home/student_28/Files/Lab_4/pulpino_students/rtl/config.sv]
set_property is_global_include true [get_files /home/student_28/Files/Lab_4/pulpino_students/rtl/config.sv]
set_property file_type "Verilog Header" [get_files /home/student_28/Files/Lab_4/pulpino_students/rtl/includes/axi_bus.sv]
set_property file_type "Verilog Header" [get_files /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_event_unit/include/defines_event_unit.sv]
set_property file_type "Verilog Header" [get_files /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/include/apu_macros.sv]
set_property file_type "Verilog Header" [get_files /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/include/zeroriscy_config.sv]
read_mem {
  /home/student_28/Files/Lab_4/pulpino_students/sw/test_sw_emb_text.dat
  /home/student_28/Files/Lab_4/pulpino_students/sw/test_sw_emb_data.dat
  /home/student_28/Files/Lab_4/pulpino_students/sw/boot_code.dat
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/keys.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/S_box.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/S_box_inverted.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_16.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_32.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_133.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_148.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_192.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_194.mem
  /home/student_28/Files/Lab_4/pulpino_students/rtl/look_up_tables/L_muliplications/L_251.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_axi_biu.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_axi_module.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_or1k_biu.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_or1k_module.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_or1k_status_reg.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_top.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adv_dbg_if.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb2per/apb2per.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/includes/apb_bus.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_event_unit/apb_event_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_fll_if/apb_fll_if.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_gpio/apb_gpio.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_i2c/apb_i2c.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_node/apb_node.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_node/apb_node_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_pulpino/apb_pulpino.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_spi_master/apb_spi_master.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_timer/apb_timer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/include/apu_core_package.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi2apb/axi2apb.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi2apb/axi2apb32.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/axi2apb_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_AR_allocator.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_AW_allocator.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_ArbitrationTree.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_BR_allocator.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_BW_allocator.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_DW_allocator.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_FanInPrimitive_Req.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_RR_Flag_Req.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_address_decoder_AR.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_address_decoder_AW.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_address_decoder_BR.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_address_decoder_BW.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_address_decoder_DW.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice/axi_ar_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice/axi_aw_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice/axi_b_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_mem_if_DP/axi_mem_if_SP.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/axi_mem_if_SP_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_multiplexer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_node.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/axi_node_intf_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice/axi_r_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_mem_if_DP/axi_read_only_ctrl.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_request_block.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_node/axi_response_block.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice/axi_slice.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/axi_slice_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/axi_spi_slave.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/axi_spi_slave_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice/axi_w_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_mem_if_DP/axi_write_only_ctrl.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/boot_code.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/boot_rom_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/clk_rst_gen.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/cluster_clock_gating.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/cluster_clock_inverter.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/cluster_clock_mux2.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/core2axi/core2axi.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/core2axi_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/core_region.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/includes/debug_bus.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/generic_fifo.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_event_unit/generic_service_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_i2c/i2c_master_bit_ctrl.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_i2c/i2c_master_byte_ctrl.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/instr_ram_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/kuznechik_cipher.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/kuznechik_cipher_apb_wrapper.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/periph_bus_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/peripherals.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/pulp_clock_inverter.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/pulp_clock_mux2.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/pulpino_top.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/ram_mux.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_L0_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/include/riscv_defines.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_alu.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_alu_div.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_apu_disp.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_compressed_decoder.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_core.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_cs_registers.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_debug_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_decoder.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_ex_stage.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_fetch_fifo.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_hwloop_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_hwloop_regs.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_id_stage.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_if_stage.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_int_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_load_store_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_mult.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_prefetch_L0_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_prefetch_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/riscv/riscv_register_file.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/components/rstgen.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_event_unit/sleep_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/sp_ram_wrap.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_spi_master/spi_master_apb_if.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_master/spi_master_clkgen.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_master/spi_master_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_master/spi_master_fifo.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_master/spi_master_rx.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_master/spi_master_tx.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_axi_plug.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_cmd_parser.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_dc_fifo.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_regs.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_rx.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_syncro.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_spi_slave/spi_slave_tx.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_timer/timer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/include/zeroriscy_defines.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_alu.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_compressed_decoder.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_core.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_cs_registers.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_debug_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_decoder.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_ex_block.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_fetch_fifo.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_id_stage.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_if_stage.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_int_controller.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_load_store_unit.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_multdiv_fast.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_multdiv_slow.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_prefetch_buffer.sv
  /home/student_28/Files/Lab_4/pulpino_students/submodules/zero-riscy/zeroriscy_register_file_ff.sv
  /home/student_28/Files/Lab_4/pulpino_students/rtl/pulpino_nexys_a7.sv
}
read_verilog -library xil_defaultlib {
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_crc32.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_tap_defines.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_tap_top.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice_dc/dc_data_buffer.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice_dc/dc_full_detector.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice_dc/dc_synchronizer.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice_dc/dc_token_ring.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice_dc/dc_token_ring_fifo_din.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/axi/axi_slice_dc/dc_token_ring_fifo_dout.v
  /home/student_28/Files/Lab_4/pulpino_students/rtl/xilinx_spram.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_axi_defines.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_defines.v
  /home/student_28/Files/Lab_4/pulpino_students/submodules/adv_dbg_if/rtl/adbg_or1k_defines.v
}
read_vhdl -library xil_defaultlib {
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/apb_uart.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_clock_div.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_counter.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_edge_detect.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_fifo.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_input_filter.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_input_sync.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/slib_mv_filter.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/uart_baudgen.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/uart_interrupt.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/uart_receiver.vhd
  /home/student_28/Files/Lab_4/pulpino_students/submodules/apb/apb_uart/uart_transmitter.vhd
}
read_ip -quiet /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xci
set_property used_in_implementation false [get_files -all /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm_board.xdc]
set_property used_in_implementation false [get_files -all /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xdc]
set_property used_in_implementation false [get_files -all /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/student_28/Files/Lab_4/pulpino_students/xdc/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files /home/student_28/Files/Lab_4/pulpino_students/xdc/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/utils_1/imports/synth_1/pulpino_nexys_a7.dcp
close [open __synthesis_is_running__ w]

synth_design -top pulpino_nexys_a7 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef -incremental_synth pulpino_nexys_a7.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pulpino_nexys_a7_utilization_synth.rpt -pb pulpino_nexys_a7_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
