#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jun 05 13:05:46 UTC 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Complex_Mult_tb_behav -key {Behavioral:sim_1:Functional:Complex_Mult_tb} -tclbatch Complex_Mult_tb.tcl -view /home/student_28/Files/Pulpino/pulpino_nexys_a7_100t/pulpino_nexys_a7_tb_behav2.wcfg -log simulate.log"
xsim Complex_Mult_tb_behav -key {Behavioral:sim_1:Functional:Complex_Mult_tb} -tclbatch Complex_Mult_tb.tcl -view /home/student_28/Files/Pulpino/pulpino_nexys_a7_100t/pulpino_nexys_a7_tb_behav2.wcfg -log simulate.log

