#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 23 18:37:01 UTC 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim pulpino_nexys_a7_tb_behav -key {Behavioral:sim_1:Functional:pulpino_nexys_a7_tb} -tclbatch pulpino_nexys_a7_tb.tcl -log simulate.log"
xsim pulpino_nexys_a7_tb_behav -key {Behavioral:sim_1:Functional:pulpino_nexys_a7_tb} -tclbatch pulpino_nexys_a7_tb.tcl -log simulate.log

