# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xci
# IP: The module: 'xilinx_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mmcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xci
# IP: The module: 'xilinx_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
