webtalk_init -webtalk_dir /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.sim/sim_1/behav/xsim/xsim.dir/pulpino_nexys_a7_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 23 18:37:34 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b3640f45-fc30-4986-bd11-760fa56847d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a027501552cb4364ad0da138265a52f0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7763 64-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2910.637 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "137.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "993305 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "11.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3778781063 -regid "" -xml /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.sim/sim_1/behav/xsim/xsim.dir/pulpino_nexys_a7_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.sim/sim_1/behav/xsim/xsim.dir/pulpino_nexys_a7_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/student_28/Files/Lab_4/pulpino_students/pulpino_nexys_a7_100t/pulpino_nexys_a7_100t.sim/sim_1/behav/xsim/xsim.dir/pulpino_nexys_a7_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
